export interface PitchDeckData {
  validationData: {
    idea: string;
    targetCustomer: string;
    problemSolved: string;
    feedback: string;
  };
  customerInsights: Array<{
    persona: {
      name: string;
      role: string;
      background: string;
      painPoints: string[];
      priceWillingness: string;
    };
    conversations?: Array<{
      question: string;
      response: string;
    }>;
  }>;
  simulationData: Array<{
    month: number;
    title: string;
    challenges: string[];
    wins: string[];
    users: number;
    keyDecisions: string[];
  }>;
  landingPageContent?: string;
}

export class TextReportGenerator {
  private parseFeedbackScore(feedback: string): number {
    const scoreMatch = feedback.match(/(\d+)\/100/);
    return scoreMatch ? parseInt(scoreMatch[1]) : 75;
  }

  private extractFeedbackSection(feedback: string, sectionTitle: string): string[] {
    const regex = new RegExp(`<h3>${sectionTitle}</h3>[\\s\\S]*?(?=<h3>|$)`, 'i');
    const match = feedback.match(regex);
    if (!match) return [];
    
    // Extract text content, remove HTML tags
    const content = match[0].replace(/<[^>]*>/g, '').replace(/\n+/g, ' ').trim();
    const lines = content.split('\n').filter(line => line.trim() && !line.includes(sectionTitle));
    return lines.length > 0 ? lines : [content.replace(sectionTitle, '').trim()];
  }

  generatePitchDeckText(data: PitchDeckData): string {
    const score = this.parseFeedbackScore(data.validationData.feedback);
    const uniqueValue = this.extractFeedbackSection(data.validationData.feedback, "What Makes This Special");
    const marketReality = this.extractFeedbackSection(data.validationData.feedback, "Market Reality Check");

    return `
STARTUP PITCH DECK
==================

${data.validationData.idea}
--------------------------

Target Customer: ${data.validationData.targetCustomer}
Problem Solved: ${data.validationData.problemSolved}

Generated by ValidatorAI - Startup Simulation Platform


THE PROBLEM
===========

Core Issue:
${data.validationData.problemSolved}

${marketReality.length > 0 ? `
Market Context:
${marketReality.map(insight => `• ${insight}`).join('\n')}
` : ''}


OUR SOLUTION
============

${data.validationData.idea}

${uniqueValue.length > 0 ? `
What Makes Us Special:
${uniqueValue.map(value => `• ${value}`).join('\n')}
` : ''}


MARKET VALIDATION
=================

Validation Score: ${score}/100

Our comprehensive validation process shows strong market fit and customer demand for this solution.


CUSTOMER RESEARCH
=================

Interviewed ${data.customerInsights.length} Target Customers:

${data.customerInsights.map(insight => `
${insight.persona.name} - ${insight.persona.role}
Background: ${insight.persona.background}
Pain Points: ${insight.persona.painPoints.join(', ')}
Price Willingness: ${insight.persona.priceWillingness}
${insight.conversations && insight.conversations.length > 0 ? `
Key Interview Insights:
Q: ${insight.conversations[0].question}
A: ${insight.conversations[0].response}
` : ''}
`).join('\n')}


BUSINESS MODEL & TRACTION
=========================

${data.simulationData && data.simulationData.length > 0 ? `
6-Month Projection:
Projected Users: ${data.simulationData[data.simulationData.length - 1].users?.toLocaleString()} users by Month 6

Key Milestones:
${data.simulationData.slice(0, 3).filter(month => month.wins && month.wins.length > 0).map(month => 
    `Month ${month.month}: ${month.wins[0]}`
).join('\n')}
` : ''}


REVENUE MODEL
=============

${data.customerInsights.some(c => c.persona.priceWillingness) ? `
Customer Price Research:
${data.customerInsights.filter(c => c.persona.priceWillingness).map(c => 
    `${c.persona.name}: ${c.persona.priceWillingness}`
).join('\n')}
` : ''}

Subscription-based model with tiered pricing to accommodate different customer segments and use cases.


NEXT STEPS
==========

${data.simulationData && data.simulationData.length > 0 && data.simulationData[0].keyDecisions ? `
Immediate Actions:
${data.simulationData[0].keyDecisions.map(decision => `• ${decision}`).join('\n')}
` : ''}

Ready to Move Forward
Based on our validation and customer research, we're ready to proceed with confidence in this market opportunity.


THANK YOU
=========

This pitch deck was generated based on AI-powered validation and customer research through ValidatorAI platform.

Ready to validate your startup idea? Visit ValidatorAI.com for free idea validation.
    `;
  }

  generateBusinessReportText(data: PitchDeckData): string {
    const score = this.parseFeedbackScore(data.validationData.feedback);
    const marketInsights = this.extractFeedbackSection(data.validationData.feedback, "Market Reality Check");

    return `
STARTUP VALIDATION REPORT
==========================

${data.validationData.idea}
Comprehensive Business Analysis

Generated by ValidatorAI


EXECUTIVE SUMMARY
=================

Business Concept: ${data.validationData.idea}
Target Market: ${data.validationData.targetCustomer}
Problem Addressed: ${data.validationData.problemSolved}

Validation Score: ${score}/100


MARKET ANALYSIS
===============

${marketInsights.length > 0 ? `
Market Insights:
${marketInsights.map(insight => `${insight}`).join('\n')}
` : ''}

Market Validation Score Breakdown:
Our validation score of ${score}/100 reflects comprehensive analysis across multiple factors including market potential, differentiation, feasibility, and problem-solution fit.


CUSTOMER RESEARCH FINDINGS
==========================

We conducted in-depth interviews with ${data.customerInsights.length} target customers to validate our assumptions and gather market insights.

${data.customerInsights.map((insight, index) => `
Customer Profile ${index + 1}: ${insight.persona.name}

Role: ${insight.persona.role}
Background: ${insight.persona.background}

Key Pain Points:
${insight.persona.painPoints.map(pain => `• ${pain}`).join('\n')}

Price Sensitivity: ${insight.persona.priceWillingness}

${insight.conversations && insight.conversations.length > 0 ? `
Interview Highlights:
${insight.conversations.map(conv => `
Q: ${conv.question}
A: ${conv.response}
`).join('')}
` : ''}
`).join('\n')}


6-MONTH BUSINESS SIMULATION
===========================

${data.simulationData && data.simulationData.length > 0 ? `
Based on our customer research and market analysis, here's a detailed month-by-month projection of your startup journey:

${data.simulationData.map(month => `
Month ${month.month}: ${month.title}
Projected Users: ${month.users?.toLocaleString()}

${month.wins && month.wins.length > 0 ? `
Key Wins:
${month.wins.map(win => `• ${win}`).join('\n')}
` : ''}

${month.challenges && month.challenges.length > 0 ? `
Challenges:
${month.challenges.map(challenge => `• ${challenge}`).join('\n')}
` : ''}

${month.keyDecisions && month.keyDecisions.length > 0 ? `
Strategic Decisions:
${month.keyDecisions.map(decision => `• ${decision}`).join('\n')}
` : ''}
`).join('\n')}
` : ''}


RECOMMENDATIONS & NEXT STEPS
=============================

Key Recommendations:
Based on our comprehensive analysis, we recommend proceeding with this business concept while focusing on the following areas:

• Customer validation through continued interviews and feedback collection
• MVP development focusing on core customer pain points
• Pricing strategy validation with target customer segments
• Market positioning to differentiate from competitors

Success Metrics to Track:
• Customer acquisition rate and cost
• User engagement and retention rates
• Revenue growth and pricing validation
• Customer satisfaction and Net Promoter Score
• Market share and competitive positioning

This report was generated through ValidatorAI's comprehensive startup validation platform.
    `;
  }

  generatePitchDeck(data: PitchDeckData): Buffer {
    const textContent = this.generatePitchDeckText(data);
    return Buffer.from(textContent, 'utf-8');
  }

  generateBusinessReport(data: PitchDeckData): Buffer {
    const textContent = this.generateBusinessReportText(data);
    return Buffer.from(textContent, 'utf-8');
  }
}